# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: laboratorio.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'laboratorio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11laboratorio.proto\x12\x0blaboratorio\"#\n\x15\x43onsultarPorIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"P\n\x16\x43onsultarPorIdResponse\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65partamento\x18\x02 \x01(\t\x12\x12\n\ncapacidade\x18\x03 \x01(\x05\x32o\n\x12LaboratorioService\x12Y\n\x0e\x43onsultarPorId\x12\".laboratorio.ConsultarPorIdRequest\x1a#.laboratorio.ConsultarPorIdResponseB\x1b\n\x17javafx.laboratorio.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'laboratorio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027javafx.laboratorio.grpcP\001'
  _globals['_CONSULTARPORIDREQUEST']._serialized_start=34
  _globals['_CONSULTARPORIDREQUEST']._serialized_end=69
  _globals['_CONSULTARPORIDRESPONSE']._serialized_start=71
  _globals['_CONSULTARPORIDRESPONSE']._serialized_end=151
  _globals['_LABORATORIOSERVICE']._serialized_start=153
  _globals['_LABORATORIOSERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
