# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import laboratorio_pb2 as laboratorio__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in laboratorio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LaboratorioServiceStub:
    """Serviço exposto pelo servidor Python
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarPorId = channel.unary_unary(
                '/laboratorio.LaboratorioService/ConsultarPorId',
                request_serializer=laboratorio__pb2.ConsultarPorIdRequest.SerializeToString,
                response_deserializer=laboratorio__pb2.ConsultarPorIdResponse.FromString,
                _registered_method=True)


class LaboratorioServiceServicer:
    """Serviço exposto pelo servidor Python
    """

    def ConsultarPorId(self, request, context):
        """RPC unário: recebe o ID e retorna os dados do laboratório
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LaboratorioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarPorId': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarPorId,
                    request_deserializer=laboratorio__pb2.ConsultarPorIdRequest.FromString,
                    response_serializer=laboratorio__pb2.ConsultarPorIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'laboratorio.LaboratorioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('laboratorio.LaboratorioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LaboratorioService:
    """Serviço exposto pelo servidor Python
    """

    @staticmethod
    def ConsultarPorId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laboratorio.LaboratorioService/ConsultarPorId',
            laboratorio__pb2.ConsultarPorIdRequest.SerializeToString,
            laboratorio__pb2.ConsultarPorIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
